[build]
  functions = "netlify/functions"
  publish = "."  # Ensure this points to the directory containing your index.html

[dev]
  port = 55555
  publish = "."  # Ensure this points to the directory containing your index.html

#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
