version: '3.8'

services:
  wealthpsychology-app:
    image: knkrn5/wealthpsychology-app-server:v1.0.1
    ports:
      - "3000:55555"
    environment:
      CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID}
      CONTENTFUL_ACCESS_TOKEN: ${CONTENTFUL_ACCESS_TOKEN}
      WS_DB_HOST: ${WS_DB_HOST}
      WS_DB_PORT: ${WS_DB_PORT}
      WS_DB_USER: ${WS_DB_USER}
      WS_DB_PASSWORD: ${WS_DB_PASSWORD}
      WS_DB_DATABASE: ${WS_DB_DATABASE}
