name: Cleanup Artifacts

on:
  schedule:
    - cron: '0 0 * * 0' # This runs the cleanup every week
  workflow_dispatch: # Allows you to manually trigger it

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup Old Artifacts
        uses: xt0rted/delete-artifact@v1.0.4
        with:
          age: 7 # Deletes artifacts older than 7 days
          per_page: 100 # Maximum number of artifacts to process per run
          token: ${{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}} # Access token
